import * as React from 'react';
import Link from 'next/link';
import Container from '@mui/material/Container';
import Footer from '../components/Footer';
import Header from '@/components/Header';


// import './globals.css'
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

// import CssBaseline from '@mui/material/CssBaseline';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



const sections = [
  { title: 'Technology', url: '#' },
  { title: 'Design', url: '#' },
  { title: 'Culture', url: '#' },
  { title: 'Business', url: '#' },
  { title: 'Politics', url: '#' },
  { title: 'Opinion', url: '#' },
  { title: 'Science', url: '#' },
  { title: 'Health', url: '#' },
  { title: 'Style', url: '#' },
  { title: 'Travel', url: '#' },
];











export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <ThemeRegistry>

        {/* <CssBaseline /> */}



          <Container maxWidth="lg">


            <Header title="Blog" sections={sections} />



            {/* <main className={styles.main}> */}
            <main>




              {children}




            </main>










          </Container>






          <Footer
            title="Footer"
            description="Something here to give the footer a purpose!"
          />




        </ThemeRegistry>
      </body>
    </html>
  )
};